---
title: कछुआ हिमलव
hero_image: images/banner.png
description: Python (पायथन) कछुए के साथ स्नोफ्लेक बनाने के लिए कोड लिखें
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: गहरा नीला
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
  - title: परिचय
  - title: आपको किसकी ज़रूरत होगी
  - title: Python Turtle (पायथन कछुए) के साथ कैसे बनाएँ
  - title: Python Turtle के साथ कैसे मुड़ें
  - title: आकार बनाने के लिए लूप का उपयोग करना
  - title: घुमावदार पैटर्न बनाना
  - title: पेन के रंग को यादृच्छिक रूप से बदलना
  - title: स्नोफ्लेक बनाने के लिए एक फंक्शन का उपयोग करना
  - title: "चुनौती: हर स्नोफ्लेक अलग होता है"
