---
title: Flocos de neve com Turtle
hero_image: images/banner.png
description: Escreva um código para desenhar flocos de neve com Python Turtle
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: navy
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
  - title: Introdução
  - title: O que você vai precisar
  - title: Como desenhar com Python Turtle
  - title: Como virar com Python Turtle
  - title: Usando laços para criar formas
  - title: Criando padrões em espiral
  - title: Mudando a cor da caneta aleatoriamente
  - title: Usando uma função para desenhar um floco de neve
  - title: "Desafio: cada floco de neve é diferente"
