---
title: Flocons de neige avec Turtle
hero_image: images/banner.png
description: Écrit du code pour dessiner des flocons de neige avec Turtle de Python
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: navy
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Ce dont tu auras besoin
- title: Comment dessiner avec Turtle de Python
- title: Comment tourner avec Turtle de Python
  completion:
  - engaged
- title: Utiliser des boucles pour créer des formes
- title: Créer des motifs en spirale
- title: Changement aléatoire de la couleur du stylo
- title: Utiliser une fonction pour dessiner un flocon de neige
  completion:
  - internal
- title: 'Défi: chaque flocon de neige est différent'
